resources:
- name: tetris-git
  type: git
  icon: github
  source:
    uri: https://github.com/taylordeckard/tetris.git
    username: (("github".access_token))
    password: x-oauth-basic
    branch: main

jobs:
- name: set-self
  plan:
  - get: tetris-git
    trigger: true
  - set_pipeline: deploy-tetris
    file: tetris-git/concourse/deploy.yaml
- name: configure
  plan:
  - get: tetris-git
    passed: [set-self]
    trigger: true
  - task: build-react
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: node
          tag: 14-alpine
      inputs:
      - name: tetris-git
      params:
        PUBLIC_URL: https://taylordeckard.me/tetris
      run:
        path: ash
        args:
        - -c
        - |
          set -e
          apk update
          apk add openssh rsync
          mkdir -p ~/.ssh
          echo "((nfs.private_key))" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan 10.0.1.198 >> ~/.ssh/known_hosts
          cd tetris-git
          npm i
          npm run build
          chmod -R 777 build
          ssh concourse@10.0.1.198 mkdir -p /mnt/shared/cdn/tetris
          rsync -r build/* concourse@10.0.1.198:/mnt/shared/cdn/tetris
